### ISSUE TITLE
Potentially malicious link in the readme 

### ISSUE THREAD

**Issue by gusandrews** [CiviCERT/suspicious-email-submitter#10]
Hi maintainers. https://phishdetect.io registration has apparently expired and it's now being squatted by what appears to be a cryptocurrency. Probably the link should be removed?

**Comment by liliakai** [comment]
Has anyone heard from Claudio lately?? I actually emailed him about it back in January when I too noticed the website had been squatted, but I didn't get an response.

Anyway, the link is removed for now. Thanks for flagging, Gus.
