### ISSUE TITLE
[tracking] explore integration with PhishDetect

### ISSUE THREAD

**Issue by mfc** [CiviCERT/suspicious-email-submitter#9]
https://github.com/phishdetect/phishdetect-extension/

discussing with amnesty team to understand possibilities of collaboration

**Comment by liliakai** [comment]
Looks like PhishDetect could implement SES functionality quite easily by taking `misp.js` from SES. They are already using the gmail-js module which has a function for extracting the raw MIME email content, so it's simply a matter of calling that function and piping the result to our `mailToMisp()` function.

**Comment by mfc** [comment]
thanks for doing that investigation, super helpful. let's create an email thread on this w/ Amnesty

**Comment by liliakai** [comment]
Just tagging this exploration by Claudio for reference: https://github.com/phishdetect/phishdetect-extension/commit/7d261ca71da31a59e27ece9fba3491741cea5e6e

**Comment by mfc** [comment]
we have gone forward with this integration work and it will be done in the https://github.com/phishdetect/phishdetect-extension/ repo
